name: GitHub Actions Cloud Run

on:
  #push:
  #  branches: [ "master" ]
  workflow_dispatch:
    inputs:
      env:
        type: choice
        default: dv
        description: "Select the Environment"
        required: true
        options:
          - dv

env:
  PROJECT_ID: terraform-workspace-413615
  PROJECT_NO: 612251736587
  SERVICE: springboot-cloudsql-run
  REGION: us-central1
  REPO: my-repo
  APP: quickstart-springboot

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
            java-version: '17'
            distribution: 'adopt'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          create_credentials_file: 'true'
          workload_identity_provider: 'projects/${{env.PROJECT_NO}}/locations/global/workloadIdentityPools/gh-identity-pool4/providers/gh-provider'
          service_account: 'gcp-github-access@${{env.PROJECT_ID}}.iam.gserviceaccount.com'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 363.0.0'

      - name: Configure Docker Client of Gcloud
        run: |-
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Build and push image
        run: |-
            docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ env.APP }}:${{ github.sha }} .
            docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ env.APP }}:${{ github.sha }}

      #gcloud builds submit \
      # --tag ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ env.APP }}:${{ github.sha }}
      # --project= ${{ env.PROJECT_ID }}
      
      - name: run terraform commands
        run: |
          gcloud config set project ${{env.PROJECT_ID}}      
          gcloud artifacts packages list --repository=${{ env.REPO }} \
          --location=${{ env.REGION }}

      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy ${{ env.SERVICE }} \
            --image ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ env.APP }}:${{ github.sha }} \
            --region ${{ env.REGION }} \
            --allow-unauthenticated \
            --service-account=cloudsql-service-account-id@${{ env.PROJECT_ID }}.iam.gserviceaccount.com \
            --vpc-connector private-cloud-sql
